spring.application.name=control_escolar

spring.datasource.url = jdbc:mysql://localhost:3306/test2
spring.datasource.username = root
spring.datasource.password = root

# A hibernate dialect gives information to the framework of how to convert hibernate queries(HQL) into native SQL queries.
spring.jpa.properties.hibernate.dialect = org.hibernate.dialect.MySQLDialect
spring.jpa.hibernate.ddl-auto=create
spring.jpa.generate-ddl=true
spring.jpa.show-sql=true